### ISSUE TITLE
Time incorrect in large files with many chapters

### ISSUE THREAD

**Issue by oberon0470** [nu774/m4acut#6]
When I use m4acut on a large file with a lot of chapters everything looks & plays fine. But if I concatenate the files with mp4box the timing is wrong. The total time for all the chapters is longer than the original file. It shows the correct number of chapters but when I play it starts in the middle of a chapter. When I concatenate the same files with ffmpeg I get a message like this for every track:

ct timestamps in the output file.
[ipod @ 00000000004f7200] Non-monotonous DTS in output stream 0:0; previous: 2222166728, current: 2222164600; changing to 2222166729. This may result in incorrect timestamps in the output file.

After concatenating with ffmpeg it does play ok. All chapters start at the beginning. Mp4box works fine on original qaac encoded files just not on a m4a split with m4acut. FFmpeg does not give the message on original qaac encoded files either.

**Comment by nu774** [comment]
> When I use m4acut on a large file with a lot of chapters everything looks & plays fine. But if I concatenate the files with mp4box the timing is wrong. 

Why do you think that it's an issue of m4acut (not mp4box) then?

Maybe you expect that cutting / concatenating is losslessly reversible simple operation, but things are not so simple.

AAC files are constantly framed (1024 samples per frame), and we can cut AAC files only at frame boundaries.
When the cut start point is not exactly on the AAC frame boundary, we have to cut at the frame boundary just before the cut point.
Similarly, as for the cut end point , we have to cut at the frame boundary just after the end point.
So, resulting AAC file would usually be a bit longer than wanted.
When you simply concatenate the resulting files, each pieces would overlap at each connection point, by 1 AAC frame at most.
Therefore, in order to correctly concatenate the files cut by m4acut, one cannot blindly concatenate AAC 
 frames, which mp4box would do. 

To achieve "sample accurate" cutting, m4acut uses iTunes metadata called iTunSMPB to store sample accurate start point and the duration of the file.
Players capable of gapless playback would see it and trim the beginning and ending of the decoded samples on playback.

**Comment by oberon0470** [comment]
If I use ffmpeg with start and stop time to cut the chapters the time is the same as the original concatenated m4a and then mp4box concatenates everything fine. I also don't get the error message in ffmpeg. I can use ffmpeg and everything works fine. It's just a lot slower than m4acut. You are right that the time drifts further and further as you go. By the last chapter it is starting 38 seconds into it. I did try deleting the iTunSMPB tags to see if that changed anything and it didn't. The original concatenated book has 135 chapters and the length is 22:28:11. After I redo it then the book is 22:30:18. Anyway I really like and use a lot of your programs and just thought that since ffmpeg could do it without issues that maybe m4acut could also.

**Comment by nu774** [comment]
> Anyway I really like and use a lot of your programs and just thought that since ffmpeg could do it without issues that maybe m4acut could also.

It's not possible.
ffmpeg's way is not sample accurate. ffmpeg just cuts at the nearest AAC frame boundary, therefore it is NOT sample accurate, it can discard samples after the specified cut start point or before the cut end point, and the resulting files are not gaplessly played back.
If you can live with that roughness, just live with it and forget about m4acut.

I didn't mention all the technical details in the previous answer, but AAC is an MDCT based codec that have overlapped nature where each frame is dependent on previous frame to decode.
AAC always needs certain amount of priming samples at the beginning to decode. Therefore m4acut always includes preceding AAC frame before the cut start point as priming.
Glitchless, gapless playback is not possible without all these care.

**Comment by Murilo-Perrone** [comment]
I get the exact same error from ffmpeg when I try to extract audio from an mp4 file generated by `Microsoft Powerpoint for Mac`. All ffmpeg operations with this file will result in numerous problems in the audio - glitches, gaps, skips, pitch distortions and repetitions. Curiously, even youtube will have problems processing this file generated from Powerpoint.

To date, the only workaround I know is to open the video in QuickTime Player, then use it to re-encode the audio (`File->Export...->Audio only...`). It produced a `ISO Media, Apple iTunes ALAC/AAC-LC (.M4A) Audio` file. Then I can re-merge audio and video back together and everything is fine with ffmpeg and youtube.

Hope that helps. Let me know if there is any other workaround which does not depend on QuickTime.
